import { Box, Typography } from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';

import Layout from '../../components/layout';

import { COLORS } from '../../utils/constants';

const useStyles = makeStyles(theme => ({
    root: {
        marginTop: theme.spacing(8.1),

        [theme.breakpoints.down('sm')]: {
            marginTop: theme.spacing(7),
            paddingLeft: theme.spacing(2),
            paddingRight: theme.spacing(2)
        }
    },

    content: {
        backgroundColor: COLORS.darkTeal,
        position: 'absolute',
        left: 0,
        top: 0,
        width: '100vw',
        height: '80vh',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',

        [theme.breakpoints.down('md')]: {
            height: '50vh'
        },
        [theme.breakpoints.down('sm')]: {
            height: '40vh'
        },

        '& h4:first-child': {
            color: COLORS.offWhite,
            fontWeight: 800
        }
    },

    container: {
        marginTop: theme.spacing(75),
        padding: [[theme.spacing(2), theme.spacing(10), theme.spacing(10), theme.spacing(10)]],

        [theme.breakpoints.down('sm')]: {
            marginTop: theme.spacing(45),
            padding: [[theme.spacing(2), theme.spacing(3), theme.spacing(3), theme.spacing(3)]]
        },
    },

    item: {
        marginBottom: theme.spacing(10),

        '& h6': {
            fontWeight: 300,
            marginBottom: theme.spacing(5)
        },

        '& p': {
            color: COLORS.offBlack,
            lineHeight: 1.9,
            marginBottom: theme.spacing(0.5),
            fontSize: theme.spacing(1.8),
            fontWeight: 300,
            textAlign: 'justify'
        }
    }
}));

const TermsAndConditions = () => {
    const classes = useStyles();

    return (
        <Layout
            title="Terms &amp; Conditions"
            // description="Your trusted P2P currency exchange platform. FXBLOOMS is committed to making currency exchange more accessible, secure and seamless."
        >
            <Box component="section" className={classes.root}>
                <Box component="header" className={classes.content}>
                    <Typography variant="h4">Terms &amp; Conditions</Typography>
                </Box>
                <Box component="section" className={classes.container}>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">General</Typography>
                        <Typography variant="body2" component="p">
                            The owner of this website (hereinafter the Website) is FXBLOOMS OÜ (registry code 16262446), address Harju maakond, Tallinn, Lasnamäe linnaosa, Tuha tn 3, 11415 Estonia (hereinafter the Owner). The purpose of the following provisions in these terms and conditions (hereinafter the Terms and Conditions) is to govern the use of the Website for persons that may come here as visitors, potential users and/or customers, partners or have any other type of interest in exchanging currencies (hereinafter the User).
                        </Typography>
                        <Typography variant="body2" component="p">
                            In the context of the Terms and Conditions, the following terms "We," "Us," or "Our," refer to the Owner.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The term "You" in the context of the Terms and Conditions refer to the User.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Services refer to providing a platform for peer-to-peer currency exchange, where people find mutually interested other people in order to exchange currencies at a rate negotiated by themselves.
                        </Typography>
                        <Typography variant="body2" component="p">
                            You confirm that you have read all the terms herein and agree that you have clearly understood and accepted the Terms and Conditions and in case You do not agree or fail to comply with the conditions herein You are not entitled to engage in using the Website.
                            Cookies are a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">RESTRICTIONS</Typography>
                        <Typography variant="body2" component="p">
                            You agree not to, and You will not permit others to:
                        </Typography>
                        <Typography variant="body2" component="p">
                            license, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the Website or make the platform available to any third party;
                        </Typography>
                        <Typography variant="body2" component="p">
                            modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the Website;
                        </Typography>
                        <Typography variant="body2" component="p">
                            remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of the Owner or its affiliates, partners, suppliers or the licensors of the Website;
                        </Typography>
                        <Typography variant="body2" component="p">
                            use the Website in any way that violates national and/or international applicable laws and regulations;    
                        </Typography>
                        <Typography variant="body2" component="p">
                            introduce any viruses, trojan horses, logic bombs, worms or other material which is malicious or technologically harmful; 
                        </Typography>
                        <Typography variant="body2" component="p">
                            attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Website, the server on which the Website is stored, or any server, computer or database connected to the Website.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The Owner is a limited liability company registered in Estonia. Access to the Website or services/products offered on the Website by certain persons or in certain countries may be contrary to the law. It is the User’s responsibility to determine whether the use of the Website and/or services/products offered on the Website are in compliance with the local applicable regulations.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Services offered, regardless of their manner of presentation on the Website, shall not be deemed as a proposal to enter into contract neither as providing investment opportunities nor advice.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">LINKS TO OTHER WEBSITES</Typography>
                        <Typography variant="body2" component="p">
                            The Website may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party’s site. We strongly advise You to review the terms and conditions of every site You visit.    
                        </Typography>
                        <Typography variant="body2" component="p">
                            We have no control over and assume no responsibility for the content, terms and conditions or practices of any third-party sites or services.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">COOKIES</Typography>
                        <Typography variant="body2" component="p">
                            The Owner uses cookies (hereinafter a Cookie) to identify the areas of Our website that You have visited.
                        </Typography>
                        <Typography variant="body2" component="p">
                            A Cookie is a small piece of data stored on Your computer or mobile device by Your web browser. We use Cookies to personalize the Content that You see on Our Website. Most web browsers can be set to disable the use of Cookies. However, if You disable Cookies, You may not be able to access functionality of Our website correctly or at all. You can read our Privacy Policy to learn more about Cookies and their functionalities.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">MODIFICATIONS TO THE WEBSITE</Typography>
                        <Typography variant="body2" component="p">
                            The Owner reserves the right to modify, suspend or discontinue, temporarily or permanently, the Website or any service to which it connects, without notice and without liability to the User.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The Owner may from time to time provide enhancements or improvements to the features/functionality of the Website, which may include patches, bug fixes, updates, upgrades and other modifications.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Updates may modify or delete certain features and/or functionality of the Website. You agree that the Owner has no obligation to provide any updates or continue to provide or enable any particular features and/or functionalities of the website to the User.
                        </Typography>
                        <Typography variant="body2" component="p">
                        You further agree that all updates will be deemed to constitute an integral part of the website, and subject to the Terms and Conditions.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">THIRD PARTY SERVICES</Typography>
                        <Typography variant="body2" component="p">
                            We may display, include or make available third-party content (including data, information, applications and other products / services) or provide links to third-party websites or services (hereinafter referred to as Third-Party Services).
                        </Typography>
                        <Typography variant="body2" component="p">
                            You acknowledge and agree that the Owner shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. The Owner does not assume and shall not have any liability or responsibility to the User or any other person or entity for any Third-Party Services.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Third-Party Services and links thereto are provided solely as a convenience to You and You access and use them entirely at Your own risk and subject to such third parties’ terms and conditions.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">INDEMNIFICATION</Typography>
                        <Typography variant="body2" component="p">
                            You agree to indemnify and hold the Owner and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys’ fees, arising out of Your use of the website or violation of any right of a third party.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">NO WARRANTIES</Typography>
                        <Typography variant="body2" component="p">
                            The Website is provided to You "as is" and „as available" and with all faults and defects without warranty of any kind.
                        </Typography>
                        <Typography variant="body2" component="p">
                            To the maximum extent permitted under applicable law, the Owner, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website, including all implied warranties or merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Without limitation, the Owner provides no warranty or undertaking, and makes no representation of any kind that the Website will meet the User’s requirements, achieve any intended results, be compatible or work with any other software, systems, or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Without limitation, the Owner shall not make any representation or warranty of any kind, express or implied:
                        </Typography>
                        <Typography variant="body2" component="p">
                            as to the operation or availability of the Website, or the information, content, and materials or products included thereon;
                        </Typography>
                        <Typography variant="body2" component="p">
                            that the Website will be uninterrupted or error-free;
                        </Typography>
                        <Typography variant="body2" component="p">
                            as to the accuracy, reliability, or currency of any information or content provided through the Website;
                        </Typography>
                        <Typography variant="body2" component="p">
                            that the Website, its servers, the content, or e-mails sent from or on behalf of the Owner are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">PRIVACY POLICY</Typography>
                        <Typography variant="body2" component="p">
                            In order to operate the Website, the Owner employs third party service providers that may process personal data for the purpose of providing services and/or for the purpose of compliance with legal obligations. The Owner undertakes to adhere to best practices and principles of personal data processing, compliant with all applicable legislation, including the European Union General Data Protection Regulation. Any personal data processed shall be processed in a fair and transparent manner. The Owner limits the amount of personal data collected to what is required for efficient operation of the Website. The Owner implements security measures necessary to ensure the confidentiality, security and integrity of collected personal data.
                        </Typography>
                        <Typography variant="body2" component="p">
                            Details on how personal data is collected, stored, secured and processed is described in the Privacy Policy of the Owner which is an integral part of the basis for the service provision.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">DISCLAIMER</Typography>
                        <Typography variant="body2" component="p">
                            The Owner is not responsible for any content, code or any other imprecision.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The Owner does not provide warranties or guarantees.
                        </Typography>
                        <Typography variant="body2" component="p">
                            In no event shall the Owner be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Website.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The Owner reserves the right to make additions, deletions, or modifications to the contents on the Website at any time without prior notice.
                        </Typography>
                    </Box>
                    <Box component="div" className={classes.item}>
                        <Typography variant="h6">APPLICABLE LAW</Typography>
                        <Typography variant="body2" component="p">
                            All matters relating to the Website or any particular products/services offered on the Website and all matters related to these Terms and Conditions and any claims or disputes arising therefrom or related thereto, shall be governed by the laws of Estonia without giving effect to any choice or conflict of law provision or rule.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The Harju County Court shall have an exclusive jurisdiction to solve any disputes or claims if it is not possible to settle them in an extrajudicial manner.
                        </Typography>
                        <Typography variant="body2" component="p">
                            In no event shall the Owner be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Website.
                        </Typography>
                        <Typography variant="body2" component="p">
                            The Owner presumes that the User has understood and accepted the current “Terms and Conditions”, and “Privacy policy” before using the Website.
                        </Typography>
                    </Box>
                </Box>
            </Box>
        </Layout>
    );
};

export default TermsAndConditions;